// src/components/EditorDropdownSidebar.tsx

import React, { useEffect, useRef, useState } from "react";
import { Sparkles, Wand2, ListPlus, Type, Image as ImageIcon, Palette, X, Loader2, CheckSquare, Square } from "lucide-react";
import { CertificateElement } from "../types/certificate";

interface SidebarItem {
  id: string;
  icon: React.ReactNode;
  label: string;
}

interface EditorDropdownSidebarProps {
  onWidthChange?: (width: number) => void;
  onAutoBulkUpload: (file: File) => void;
  
  // Context for AI Panel
  selectedElement?: CertificateElement; 
  isGenerating?: boolean;
  
  // ⭐️ NEW PROPS FOR BULK CONTROL
  isBulkMode?: boolean;
  bulkCount?: number;
  
  // Updated Signature to include the "applyToAll" boolean
  onAiGenerate?: (prompt: string, applyToAll: boolean) => Promise<void>;
}

const SIDEBAR_WIDTH = 80; 

const LAYER_NAMES: Record<number, string> = {
  1: "Background Layer",
  2: "Border",
  3: "Inner Frame",
  4: "Corner Frames",
  5: "Watermark",
  18: "Logo"
};

const EditorDropdownSidebar: React.FC<EditorDropdownSidebarProps> = ({ 
  onWidthChange, 
  onAutoBulkUpload, 
  selectedElement,
  onAiGenerate,
  isGenerating = false,
  isBulkMode = false,
  bulkCount = 0
}) => {
  
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [activePanel, setActivePanel] = useState<string | null>(null);
  const [promptText, setPromptText] = useState("");
  
  // ⭐️ NEW STATE: Checkbox for "Apply to All"
  const [applyToAll, setApplyToAll] = useState(true);

  const sidebarItems: SidebarItem[] = [
    { id: "ai-autofill", icon: <Sparkles size={20} />, label: "AI Autofill" },
    { id: "ai-design", icon: <Wand2 size={20} />, label: "AI Design" },
    { id: "auto-bulk", icon: <ListPlus size={20} />, label: "Auto Bulk" },
    { id: "text", icon: <Type size={20} />, label: "Text" },
    { id: "image", icon: <ImageIcon size={20} />, label: "Image" },
    { id: "brand-kit", icon: <Palette size={20} />, label: "Brand Kit" },
  ];

  const handleBulkClick = () => {
    if (fileInputRef.current) fileInputRef.current.click();
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      onAutoBulkUpload(file);
    }
    if (fileInputRef.current) fileInputRef.current.value = ""; 
  };

  const handleItemClick = (id: string) => {
    if (id === 'auto-bulk') {
      handleBulkClick();
    } else if (id === 'ai-design') {
      setActivePanel(activePanel === 'ai-design' ? null : 'ai-design');
    } else {
      setActivePanel(null);
    }
  };

  const handleGenerateClick = () => {
    if (onAiGenerate && promptText.trim()) {
      // ⭐️ PASS CHECKBOX STATE TO PARENT
      onAiGenerate(promptText, applyToAll);
    }
  };

  const getAiPanelContent = () => {
    if (!selectedElement) {
      return (
        <div className="text-slate-400 text-sm text-center italic mt-4">
          Please select an element on the canvas to regenerate.
        </div>
      );
    }

    if (selectedElement.type === 'text' || selectedElement.type === 'signature') {
      return (
        <div className="text-red-400 text-sm text-center mt-4 border border-red-500/30 bg-red-500/10 p-3 rounded">
          Text fields cannot be regenerated by AI Design. Please select an image, background, or frame.
        </div>
      );
    }

    let layerName = LAYER_NAMES[selectedElement.zIndex || 0] || `Layer (Index: ${selectedElement.zIndex})`;
    if (selectedElement.zIndex === 4) {
      layerName = "Corner Frames (Layer 4)";
    }

    return (
      <div className="flex flex-col gap-3 mt-2">
        <div className="bg-slate-800 p-2 rounded border border-slate-600 text-xs text-cyan-400 font-mono text-center">
          SELECTED: {layerName.toUpperCase()}
        </div>

        <label className="text-xs text-slate-400 mt-2">Describe what you want:</label>
        <textarea 
          className="w-full h-24 bg-slate-900 border border-slate-700 rounded p-2 text-sm text-white focus:border-cyan-500 focus:outline-none resize-none"
          placeholder="E.g., A minimalist golden border with floral corners..."
          value={promptText}
          onChange={(e) => setPromptText(e.target.value)}
        />

        {/* ⭐️ NEW CHECKBOX UI: Only show if in Bulk Mode */}
        {isBulkMode && (
          <div 
            className="flex items-center gap-2 mt-2 p-2 bg-slate-800/50 rounded border border-slate-700 cursor-pointer hover:bg-slate-800 transition"
            onClick={() => setApplyToAll(!applyToAll)}
          >
            <div className={`text-cyan-400 transition-all ${applyToAll ? "opacity-100" : "opacity-50"}`}>
               {applyToAll ? <CheckSquare size={16} /> : <Square size={16} />}
            </div>
            <span className="text-xs text-slate-300 select-none">
              Apply to all <strong>{bulkCount}</strong> certificates
            </span>
          </div>
        )}

        <button
          onClick={handleGenerateClick}
          disabled={isGenerating || !promptText.trim()}
          className="mt-2 w-full bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white py-2 rounded font-medium text-sm flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
        >
          {isGenerating ? (
            <>
              <Loader2 className="animate-spin" size={16} /> Generating...
            </>
          ) : (
            <>
              <Wand2 size={16} /> Generate
            </>
          )}
        </button>
        <p className="text-[10px] text-slate-500 text-center">
          Powered by DALL-E 3
        </p>
      </div>
    );
  };

  useEffect(() => {
    if (onWidthChange) {
      onWidthChange(SIDEBAR_WIDTH); 
    }
  }, [onWidthChange]);

  return (
    <>
      {/* MAIN SIDEBAR */}
      <div 
        className="fixed top-20 bottom-20 right-0 z-50 flex flex-col items-center bg-slate-900 border-l border-slate-700 shadow-2xl transition-all duration-300"
        style={{ width: `${SIDEBAR_WIDTH}px` }}
      >
        <div className="flex flex-col items-center w-full h-full p-1 overflow-y-auto"> 
          <input 
            type="file" 
            ref={fileInputRef} 
            style={{ display: 'none' }} 
            accept=".xlsx, .xls, .csv"
            onChange={handleFileChange}
          />
          {sidebarItems.map((item) => (
            <button
              key={item.id}
              onClick={() => handleItemClick(item.id)}
              className={`w-full flex flex-col items-center justify-center gap-1.5 px-0.5 py-3 my-1 rounded-lg transition border-b border-slate-700 last:border-b-0 ${
                activePanel === item.id ? 'bg-slate-800 text-cyan-400' : 'text-white hover:bg-slate-700/70'
              }`}
              title={item.label}
            >
              <div className={`flex items-center justify-center ${activePanel === item.id ? 'text-cyan-400' : 'text-slate-300'}`}>
                {item.icon}
              </div>
              <span className={`text-[10px] font-medium text-center leading-tight ${activePanel === item.id ? 'text-cyan-400' : 'text-slate-300'}`}>
                {item.label}
              </span>
            </button>
          ))}
        </div>
      </div>

      {/* EXTENDED PANEL */}
      {activePanel === 'ai-design' && (
        <div 
          className="fixed top-20 bottom-20 z-40 bg-slate-900 border-l border-slate-700 shadow-2xl flex flex-col p-4"
          style={{ 
            right: `${SIDEBAR_WIDTH}px`, 
            width: '280px',
            borderRight: '1px solid #334155' 
          }}
        >
          <div className="flex items-center justify-between mb-4 border-b border-slate-700 pb-2">
            <h3 className="font-bold text-white flex items-center gap-2">
              <Wand2 size={18} className="text-purple-400" /> AI Designer
            </h3>
            <button 
              onClick={() => setActivePanel(null)}
              className="text-slate-400 hover:text-white"
            >
              <X size={18} />
            </button>
          </div>
          {getAiPanelContent()}
        </div>
      )}
    </>
  );
};

export default EditorDropdownSidebar;